# service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${_SERVICE_NAME}
      annotations:
          run.googleapis.com/minScale: '0'
          run.googleapis.com/maxScale: '2'
spec:
  template:
    metadata:
      annotations:
        # Habilita Identity-Aware Proxy (IAP) para el servicio
        # El valor 'all' significa que solo el tráfico autorizado por IAP es permitido.
        run.googleapis.com/ingress: all
    spec:
      serviceAccountName: iot-monitor-web-sa-run@imonitor-miniups.iam.gserviceaccount.com
      containers:
      - image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}-img:${_TAG_NAME}
        resources:
          limits:
            # Recursos de CPU y Memoria (0.25 vCPU y 512 MiB de RAM)
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 8080 # Puerto que escucha tu aplicación Node.js
      timeoutSeconds: 300 # Tiempo de espera para la solicitud (opcional)
